CREATE TABLE "authorization".refresh_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token      VARCHAR(255)                            NOT NULL,
    user_id    UUID                                    NOT NULL,
    issued_at  TIMESTAMP(6) WITH TIME ZONE             NOT NULL,
    expiration TIMESTAMP(6) WITH TIME ZONE             NOT NULL,

    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
    CONSTRAINT uc_refresh_tokens_token UNIQUE (token),
    CONSTRAINT fk_refresh_tokens_on_user
        FOREIGN KEY (user_id)
            REFERENCES "authorization".users (id)
            ON DELETE CASCADE
);