server:
  port: 8080

spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false