spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  jackson:
    datatype:
      datetime:
        write-dates-as-timestamps: false

app:
  cors:
    allowed-origins: "http://localhost:5173"
  jwt:
    secret-key: cGxlbnR5aW50ZXJlc3RzYWZldHl3YWdvbnJoeXRobW0=
    expiration:
      access-minutes: 15
      refresh-minutes: 4320
  admin:
    username: admin
    email: admin@admin.com
    password: admin123
  telegram:
    bot-token: ${TELEGRAM_BOT_TOKEN}
    chat-id: ${TELEGRAM_CHAT_ID}
  cookie:
    secure: false
    same-site: ""
    partitioned: false

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: health

#logging:
#  level:
#    org.hibernate: DEBUG
#    org.springframework.boot.autoconfigure.orm.jpa: DEBUG