spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

app:
  cors:
    allowed-origins: "http://localhost:5173"

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: health